# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "zfs" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];

  fileSystems."/home/sguzman/data" = {
    device = "storage";
    fsType = "zfs";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80a1a22c-ebb1-4c4c-ae8b-7988915744d3";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6b3b1dca-7335-42da-b233-bb2c6b23d1ac"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
